lifecycle

diff --git a/packages/qwl/builtins/std/steps.yaml b/packages/qwl/builtins/std/steps.yaml
--- a/packages/qwl/builtins/std/steps.yaml
+++ b/packages/qwl/builtins/std/steps.yaml
@@ -10,14 +10,20 @@ tasks:
       description: ""
       command: ""
     cmd: |
-      local description=${1:-"{{ vars.description }}"}
+      if [ -z "${__STEP_INDENT+set}" ]; then
+        export __STEP_INDENT=""
+      fi
+
+      local description=${1:-"{{ vars.description | escape }}"}
       shift
       local command=${*:-"{{ vars.command }}"}
 
-      printf '%s %s %s\n' \
-        "{{ "┌──" | color("#808080") }} {{ "Step:" | color("blue") }} $description" \
-        "{{ "in" | color("#808080") }}" \
-        "$(echo "$PWD" | sed "s|^$HOME|~|")" >&2
+      if {{ log.tasks.should_log }} "INFO"; then
+        printf '%s %s %s %s\n' \
+          "${__STEP_INDENT}{{ "┌──" | color("#808080") }} {{ "Step:" | color("blue") }} $description" \
+          "{{ "in" | color("#808080") }}" \
+          "$(echo "$PWD" | sed "s|^$HOME|~|")" "" >&2
+      fi
 
       local truncated_command="${command:0:60}"
 
@@ -25,7 +31,7 @@ tasks:
         truncated_command="${truncated_command}..."
       fi
 
-      {{ log.tasks.debug }} "{{ "│ Executing:" | color("#808080") }} $truncated_command"
+      {{ log.tasks.debug }} "${__STEP_INDENT}{{ "│ Executing:" | color("#808080") }} $truncated_command"
 
       local start_time=$(date +%s)
 
@@ -40,27 +46,40 @@ tasks:
       local duration=$((end_time - start_time))
 
       if [ $exit_code -eq 0 ]; then
-        printf '%s\n' "{{ "└─" | color("#808080") }} {{ "✔ Success" | color("green") }} {{ "(${duration}s)" | color("#808080") }}" >&2
+        if {{ log.tasks.should_log }} "INFO"; then
+            printf '%s\n' "${__STEP_INDENT}{{ "└─" | color("#808080") }} {{ "✔ Success" | color("green") }} {{ "(${duration}s)" | color("#808080") }}" >&2
+        fi
       else
-        printf '%s\n' "{{ "└─" | color("#808080") }} {{ "✘ Failed" | color("red") }} {{ "(Exit Code: ${exit_code})" | color("#808080") }}" >&2
-        return $exit_code
+        if {{ log.tasks.should_log }} "ERROR"; then
+          printf '%s\n' "${__STEP_INDENT}{{ "└─" | color("#808080") }} {{ "✘ Failed" | color("red") }} {{ "(Exit Code: ${exit_code})" | color("#808080") }}" >&2
+          return $exit_code
+        fi
       fi
 
   compose:
     vars:
       steps: []
     cmd: |
+      # if __STEP_INDENT is undefined, set it to ""
+      if [ -z "${__STEP_INDENT+set}" ]; then
+        export __STEP_INDENT=""
+      # else increment __STEP_INDENT
+      else
+        export __STEP_INDENT="$__STEP_INDENT  "
+      fi
+
+
       local failed=false
       local failed_desc=""
 
       {% for step in vars.steps %}
       # Step: {{ step.desc }}
       if [ "$failed" = false ] || [ "{{ step.always | default(false) }}" = "true" ]; then
-        if ! {{ tasks.step }} "{{ step.desc | escape }} {{ "(always)" if step.always }}" "{{ step.cmd }}";
+        if ! {{ tasks.step }} "{{ step.desc | escape }} {{ "(always)" if step.always }}" "{{ step.cmd | escape }}";
 
         then
           failed=true
-          failed_desc="{{ step.desc }}"
+          failed_desc="{{ step.desc | escape }}"
         fi
       fi
 
@@ -68,6 +87,11 @@ tasks:
       {% endfor %}
 
       if [ "$failed" = true ]; then
-        {{ modules.log.tasks.error }} "Step \"${failed_desc}\" failed. Exiting with error."
+        {{ log.tasks.error }} "Step \"${failed_desc}\" failed. Exiting with error."
         return 1
+      fi
+
+      # decrement __STEP_INDENT by removing two spaces only if it's not empty
+      if [ -n "$__STEP_INDENT" ]; then
+        export __STEP_INDENT="${__STEP_INDENT:0:-2}"
       fi
