uv-workspace

diff --git a/packages/qwl/builtins/std/steps.yaml b/packages/qwl/builtins/std/steps.yaml
--- a/packages/qwl/builtins/std/steps.yaml
+++ b/packages/qwl/builtins/std/steps.yaml
@@ -6,39 +6,45 @@ modules:
 
 tasks:
   step:
+    vars:
+      description: ""
+      command: ""
     cmd: |
-      {{ utils.once }} "utils:color" "{{ utils.color }}"
-      {{ log.info }} "${Q_GRAY}┌── ${Q_BLUE}Step: $1${Q_RESET}"
+      local description=${1:-"{{ vars.description }}"}
+      shift
+      local command=${*:-"{{ vars.command }}"}
 
-      local command_str="$2"
-      local truncated_command_str=$(echo "$command_str" | head -c 60)
-      {{ log.debug }} "${Q_GRAY}│ Executing: ${truncated_command_str}${Q_RESET}"
+      printf '%s\n' "{{ "┌──" | color("#808080") }} {{ "Step:" | color("blue") }} $description" >&2
+
+      local truncated_command=$(echo "$command" | head -c 60)
+      {{ log.tasks.debug }} "{{ "│ Executing:" | color("#808080") }} $truncated_command"
 
       local start_time=$(date +%s)
 
-      eval "$command_str"
-      local exit_code=$?
+      bash -c "$command"
 
+      local exit_code=$?
       local end_time=$(date +%s)
       local duration=$((end_time - start_time))
 
       if [ $exit_code -eq 0 ]; then
-        {{ log.info }} "${Q_GRAY}└─ ${Q_GREEN}✔ Success${Q_GRAY} (${duration}s)${Q_RESET}"
-        return 0
+        printf '%s\n' "{{ "└─" | color("#808080") }} {{ "✔ Success" | color("green") }} {{ "(${duration}s)" | color("#808080") }}" >&2
       else
-        {{ log.error }} "${Q_GRAY}└─ ${Q_RED}✘ Failed${Q_GRAY} (Exit Code: ${exit_code})${Q_RESET}"
+        printf '%s\n' "{{ "└─" | color("#808080") }} {{ "✘ Failed" | color("red") }} {{ "(Exit Code: ${exit_code})" | color("#808080") }}" >&2
         return $exit_code
       fi
 
   compose:
     vars:
       steps: []
+    # This should not inline the steps!
     cmd: |
-      for step in "${steps[@]}"; do
-        IFS='|' read -r step_name step_command <<< "$step"
-        {{ tasks.step }} "$step_name" "$step_command"
-        local step_exit_code=$?
-        if [ $step_exit_code -ne 0 ]; then
-          return $step_exit_code
-        fi
-      done
+      {% for step in vars.steps %}
+      # Step: {{ step.desc }}
+      {% if step.as %}
+      local {{ step.as }}
+      {{ step.as }}=$({{ tasks.step }} "{{ step.desc }}" '{{ step.cmd }}')
+      {% else %}
+      {{ tasks.step }} "{{ step.desc }}" "{{ step.cmd }}"
+      {% endif %}
+      {% endfor %}
